---
- hosts: scarlat
  tasks:
    - name: Add Docker s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Verify that we have the key with the fingerprint
      apt_key:
        id: 0EBFCD88
        state: present

    - name: Set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
        state: present
        update_cache: yes

    - name: Install docker
      apt:
        name: [ "docker-ce", "docker-ce-cli", "containerd.io", "docker-compose" ]
        state: present
        update_cache: yes

    - name: Enable service docker and ensure it is not masked
      systemd:
        name: docker
        enabled: yes
        masked: no

    - name: Create "docker" group
      group:
        name: "docker"
        state: present
