name: build

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rastasheep/ubuntu-sshd

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.CI_DOCKER_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: lowitea/jeevez/bot
        registry: docker.pkg.github.com
        tags: ${{ github.event.release.tag_name }}, latest
        dockerfile: ./deploy/jeevez/Dockerfile
        cache_froms: docker.pkg.github.com/lowitea/jeevez/bot:latest
        build_args: JEEVEZ_APP_VERSION=${{ github.event.release.tag_name }}

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CI_HOST }}
        username: ${{ secrets.CI_DEPLOY_USER }}
        key: ${{ secrets.CI_DEPLOY_KEY }}
        script: |
          rm -rf jeevez_deploy
          git clone https://github.com/lowitea/jeevez.git jeevez_deploy
          cd jeevez_deploy
          echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${{ secrets.CI_DOCKER_USER }} --password-stdin
          docker pull docker.pkg.github.com/lowitea/jeevez/bot:${{ github.event.release.tag_name }}
          JEEVEZ_APP_VERSION=${{ github.event.release.tag_name }} \
          JEEVEZ_TELEGRAM_BOTNAME=${{ secrets.JEEVEZ_TELEGRAM_BOTNAME }} \
          JEEVEZ_TELEGRAM_TOKEN=${{ secrets.JEEVEZ_TELEGRAM_TOKEN }} \
          JEEVEZ_TELEGRAM_ADMIN=${{ secrets.JEEVEZ_TELEGRAM_ADMIN }} \
          JEEVEZ_DB_USER=${{ secrets.JEEVEZ_DB_USER }} \
          JEEVEZ_DB_PASSWORD=${{ secrets.JEEVEZ_DB_PASSWORD }} \
          JEEVEZ_CURRENCYAPI_TOKEN=${{ secrets.JEEVEZ_CURRENCYAPI_TOKEN }} \
          JEEVEZ_WEATHERAPI_TOKEN=${{ secrets.JEEVEZ_WEATHERAPI_TOKEN }} \
          docker-compose -f deploy/docker-compose.yml \
                         -f deploy/docker-compose.db.yml \
          	             --project-directory . \
                         up \
                         -d \
                         --force-recreate \
                         jeevez
          false
