name: build

on:
  push:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rastasheep/ubuntu-sshd

    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.CI_DOCKER_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: lowitea/jeevez/bot
        registry: docker.pkg.github.com
#        tags: ${{ github.event.release.tag_name }}, latest
        tags: latest
        dockerfile: ./deploy/jeevez/Dockerfile
