name: build

on:
  push:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.CI_DOCKER_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: jeevez/bot
        registry: docker.pkg.github.com
        tags: ${{ github.event.release.tag_name }}, latest
        dockerfile: ./deploy/jeevez/Dockerfile
