name: build

on:
  push:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rastasheep/ubuntu-sshd

    steps:
    - uses: actions/checkout@v2

#    - name: Build and push Docker image
#      uses: docker/build-push-action@v1
#      with:
#        username: ${{ secrets.CI_DOCKER_USER }}
#        password: ${{ secrets.GITHUB_TOKEN }}
#        repository: lowitea/jeevez/bot
#        registry: docker.pkg.github.com
#        tags: ${{ github.event.release.tag_name }}, latest
#        dockerfile: ./deploy/jeevez/Dockerfile

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CI_HOST }}
        username: ${{ secrets.CI_DEPLOY_USER }}
        key: ${{ secrets.CI_DEPLOY_KEY }}
        script: |
          docker pull docker.pkg.github.com/lowitea/jeevez/bot:latest
          docker rm -f jeevez
          docker run --name jeevez --rm -d -e JEEVEZ_TELEGRAM_TOKEN=${{ secrets.JEEVEZ_TELEGRAM_TOKEN }} docker.pkg.github.com/lowitea/jeevez/bot:latest
