name: build

on:
  push:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rastasheep/ubuntu-sshd

    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.CI_DOCKER_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: lowitea/jeevez/bot
        registry: docker.pkg.github.com
#        tags: ${{ github.event.release.tag_name }}, latest
        tags: latest
        dockerfile: ./deploy/jeevez/Dockerfile

    - name: Deploy
      run: |
        mkdir -p ~/.ssh
        echo "$CI_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod -R 700 ~/.ssh
        echo "$CI_DEPLOY_KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
#          ssh $CI_USER_HOST 'docker pull docker.pkg.github.com/lowitea/jeevez/bot:${{ github.event.release.tag_name }}'
        ssh $CI_USER_HOST 'docker pull docker.pkg.github.com/lowitea/jeevez/bot:latest'
        ssh $CI_USER_HOST 'docker rm -f jeevez'
#          ssh $CI_USER_HOST 'docker run --name jeevez --rm -d -e JEEVEZ_TELEGRAM_TOKEN=${{ secrets.JEEVEZ_TELEGRAM_TOKEN }} docker.pkg.github.com/lowitea/jeevez/bot:${{ github.event.release.tag_name }}'
        ssh $CI_USER_HOST 'docker run --name jeevez --rm -d -e JEEVEZ_TELEGRAM_TOKEN=${{ secrets.JEEVEZ_TELEGRAM_TOKEN }} docker.pkg.github.com/lowitea/jeevez/bot:latest'

