name: build

on:
  push:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        tags: ${{ github.event.release.tag_name }}, latest
        file: ./deploy/jeevez/Dockerfile
