name: build

on:
  push:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rastasheep/ubuntu-sshd

    steps:
    - uses: actions/checkout@v2

#    - name: Build and push Docker image
#      uses: docker/build-push-action@v1
#      with:
#        username: ${{ secrets.CI_DOCKER_USER }}
#        password: ${{ secrets.GITHUB_TOKEN }}
#        repository: lowitea/jeevez/bot
#        registry: docker.pkg.github.com
#        tags: ${{ github.event.release.tag_name }}, latest
#        dockerfile: ./deploy/jeevez/Dockerfile

    - name: Deploy
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CI_DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
        chmod -R 700 ~/.ssh
        echo "${{ secrets.CI_DEPLOY_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_ed25519
        ssh ${{ secrets.CI_USER_HOST }} 'docker pull docker.pkg.github.com/lowitea/jeevez/bot:latest'
        ssh ${{ secrets.CI_USER_HOST }} 'docker rm -f jeevez'
        ssh ${{ secrets.CI_USER_HOST }} 'docker run --name jeevez --rm -d -e JEEVEZ_TELEGRAM_TOKEN=${{ secrets.JEEVEZ_TELEGRAM_TOKEN }} docker.pkg.github.com/lowitea/jeevez/bot:latest'
